friends = ["Dick", "Dingus", "Dummy", "Cootch"]
print(friends)
print(friends[-3])
print(friends[1])
print(friends[1:])
print(friends[1:3])
friends[1] = "dimmidum"
print(friends[1])
numbers = [6, 6, 21, 8, 10, 12, 14]
print(numbers)
friends.extend(numbers)
print(numbers)
print(friends)
friends.append("Creed")
print(friends)
friends.insert(1, "dank")
print(friends)
friends.remove("Cootch")
print(friends)
numbers.sort()
print(numbers)
friends.pop()
print(friends)
print(friends.index("Dick"))
print(friends.count(6))
friends.reverse()
print(friends)
friends.clear()
print(friends)
friends.insert(0, "bob")
friends.insert(1, "Jill")
print(friends)
friends.insert(1, numbers)
